log:
  datetime: '2024-06-15 23:00:05'
  last_train_id: 4888f0b2-escalelossmin1
  saved_path: ./output/test615/white_background_ori_232_4888f0b2-escalelossmin1
param:
  pad: 15
  prune_after_iteration: 29000
train:
  use_scale_loss: True
  use_mask_pruning: True
  use_SAM_mask: True