log:
  datetime: '2024-06-28 17:09:46'
  last_train_id: 61d1b03d-atwo
  saved_path: ./output/test615/white_background_70_61d1b03d-atwo
param:
  pad: 6
  prune_after_iteration: 29000
train:
  use_SAM_mask: true
  use_dist_loss: true
  use_mask_pruning: true
  use_scale_loss: true
