log:
  datetime: '2024-06-16 15:20:32'
  last_train_id: 48487525-1test
  saved_path: ./output/test615/white_background_70_48487525-1test
param:
  pad: 15
  prune_after_iteration: 29000
train:
  use_SAM_mask: true
  use_dist_loss: true
  use_mask_pruning: true
  use_scale_loss: true
