log:
  datetime: '2024-06-28 17:43:23'
  last_train_id: 3a57df0c-fthr
  saved_path: ./output/test615/white_background_100_3a57df0c-fthr
param:
  pad: 8
  prune_after_iteration: 29000
train:
  use_SAM_mask: true
  use_dist_loss: true
  use_mask_pruning: true
  use_scale_loss: true
