log:
  datetime: '2024-07-01 16:42:31'
  last_train_id: 9a633e6f-bbackground150
  saved_path: ./output/test702/jun_background_150_9a633e6f-bbackground150
param:
  pad: 8
  prune_after_iteration: 29000
train:
  use_SAM_mask: true
  use_dist_loss: true
  use_mask_pruning: true
  use_scale_loss: true
