log:
  datetime: '2024-10-28 06:24:40'
  last_train_id: 7fd157da-3man11
  saved_path: ./output/1029/man11_7fd157da-3man11
param:
  pad: 8
  prune_after_iteration: 29000
train:
  use_SAM_mask: true
  use_dist_loss: true
  use_mask_pruning: true
  use_scale_loss: true
