log:
  datetime: '2024-07-01 18:29:37'
  last_train_id: c88bdd77-bbackground100
  saved_path: ./output/test702/jun_background_100_c88bdd77-bbackground100
param:
  pad: 8
  prune_after_iteration: 29000
train:
  use_SAM_mask: true
  use_dist_loss: true
  use_mask_pruning: true
  use_scale_loss: true
